# Generated by Django 3.1 on 2020-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20200917_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
