# Generated by Django 3.1 on 2020-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_auto_20200923_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='Adicional',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
